//GENERATED BY WOLFETPLAYER - 20-10-17
models/weapons2/grenade/grenade_us
{
	{
		map textures/effects/envmap_slate2.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/grenade/grenade_us.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/multiplayer/mg42/s_mg42
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/mg42/s_mg42.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/weapons2/luger/luger
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/luger/luger.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/multiplayer/m1_garand/m1stock
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/m1_garand/m1stock.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/multiplayer/m1_garand/m1garandscope
{
	{
		map textures/effects/envmap_slateUL.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/m1_garand/m1garandscope.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/luger/weapon_p08_c
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/luger/weapon_p08_c.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/mauser/k98_body
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mauser/k98_body.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/mauser/m1903_body
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mauser/m1903_body.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/colt/colt45
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/colt/colt45.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/colt2/colt45
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/colt2/colt45.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/silencer/weapon_silencer_ge_c
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/silencer/weapon_silencer_ge_c.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/luger/weapon_silencer_ge_c
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/luger/weapon_silencer_ge_c.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/multiplayer/m1_garand/m1rec
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/m1_garand/m1rec.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/colt/colt4
{
	{
		map textures/effects/envmap_slateUL.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/colt/colt4.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/colt2/colt4
{
	{
		map textures/effects/envmap_slateUL.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/colt2/colt4.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/colt2/colt
{
	{
		map textures/effects/envmap_slateUL.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
	{
		map models/weapons2/colt2/colt.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/weapons2/colt/colt4
{
	{
		map textures/effects/envmap_slateUL.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/colt/colt4.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/grenade/grenade
{
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/grenade/grenade.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/ammo/grenade
{
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/ammo/grenade.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/weapons2/knife/knife1a
{
	{
		map textures/effects/envmap_slate2.tga
		rgbGen lightingDiffuse
		tcMod scale 4 1
		tcGen environment 
	}
	{
		map models/weapons2/knife/knife1a.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/weapons2/knife/knife1s
{
	{
		map textures/effects/tinfxG.tga
		rgbGen lightingDiffuse
		tcMod scale 1 3
		tcGen environment 
	}
	{
		map models/weapons2/knife/knife1s.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
	{
		map textures/effects/specular3.tga
		blendfunc add
		rgbGen lightingDiffuse
		tcMod scale 1 3
		tcGen environment 
	}
}

models/weapons2/luger/luger7
{
	{
		map textures/effects/envmap_slate2.tga
		rgbGen lightingDiffuse
		tcMod scale 3 3
		tcGen environment 
	}
	{
		map models/weapons2/luger/luger7.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/weapons2/mauser/mauser3
{
	{
		map textures/effects/envmap_mp.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mauser/mauser3.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/weapons2/mp40/gun11
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcMod scale 1.05 1.05
		tcGen environment 
	}
	{
		map models/weapons2/mp40/1p_mp40_c.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/sten/sten1
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/sten/sten1.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/multiplayer/kar98_2/kar98k_third
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/kar98_2/kar98k_third.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/mauser/weapon_kar98_c
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mauser/weapon_kar98_c.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

//models/weapons2/thompson/thompson_la
//{
//	{
//		map textures/effects/metal_new.tga
//		rgbGen lightingDiffuse
//		tcGen environment 
//	}
//	{
//		map models/weapons2/thompson/thompson_la_yd.tga
//		blendfunc filter
//		rgbGen lightingDiffuse
//	}
//}

//models/weapons2/thompson/thompson_barrel
//{
//	{
//		map textures/effects/metal_new.tga
//		rgbGen lightingDiffuse
//		tcGen environment 
//	}
//	{
//		map models/weapons2/thompson/thompson_barrel.tga
//		blendfunc filter
//		rgbGen lightingDiffuse
//	}
//}

//models/weapons2/thompson/thompson_site
//{
//	{
//		map textures/effects/metal_new.tga
//		rgbGen lightingDiffuse
//		tcGen environment 
//	}
//	{
//		map models/weapons2/thompson/thompson_site.tga
//		blendfunc filter
//		rgbGen lightingDiffuse
//	}
//}

//models/weapons2/thompson/thompson_stock
//{
//	{
//		map textures/effects/metal_new.tga
//		rgbGen lightingDiffuse
//		tcGen environment 
//	}
//	{
//		map models/weapons2/thompson/thompson_stock.tga
//		blendfunc filter
//		rgbGen lightingDiffuse
//	}
//}

models/weapons2/mp34/mp34
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mp34/mp34.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/multiplayer/g43/g43
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/g43/g43.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/multiplayer/mg42/s_mg42
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/mg42/s_mg42.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/multiplayer/mg42/bullet
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/mg42/bullet.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/multiplayer/mg42/bullet_yd
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/mg42/bullet_yd.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/bar/barBarrel
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/bar/barBarrel.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/bar/barClipBolt
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/bar/barClipBolt.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/bar/barMisc
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/bar/barMisc.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/bar/barSight
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/bar/barSight.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/bar/barStock
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/bar/barStock.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/mosin/mosin
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mosin/mosin.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/mp44/stg44_c
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mp44/stg44_c.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/mp44/mp44_a
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mp44/mp44_a.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/mp44/mp44_b
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/mp44/mp44_b.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/stg44/mp44body
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/stg44/mp44body.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/stg44/mp44stock
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/stg44/mp44stock.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/weapons2/rocketl/panzerfast1a
{
    
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
      
	{
		map models/weapons2/rocketl/panzerfast1a.tga
		rgbGen lightingDiffuse
	}
}

models/weapons2/tt33/tt33
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/tt33/tt33.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/fg42/fg42
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/fg42/fg42.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/m97/shotgunBarrel
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/m97/shotgunBarrel.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/m97/shotgunStock
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/m97/shotgunStock.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/flamethrower/flame1_yd
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/flamethrower/flame1_yd.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/venom/v4
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/venom/v4.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/venom/venum1aa
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/venom/venum1aa.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/44magnum/etnam_44m
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/44magnum/etnam_44m.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/ppsh/ppsh_misc
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/ppsh/ppsh_misc.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/ppsh/ppsh_reciever
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/ppsh/ppsh_reciever.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/ppsh/ppsh_stock
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/ppsh/ppsh_stock.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

models/weapons2/tesla/base_tesla4
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/tesla/base_tesla4.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
	{
		map models/weapons2/tesla/glow1.tga
		blendfunc add
		rgbGen wave triangle 0.5 0.4 0 0.8 
	}
	{
		map models/weapons2/tesla/glow2.tga
		blendfunc add
		rgbGen wave triangle 0.5 1 0 1 
	}
	{
		map models/weapons2/tesla/base_tesla4_glow.tga
		blendfunc add
		rgbGen wave triangle 0.5 0.5 0 0.5 
	}
}

models/powerups/ammo/amtesla
{
	{
		map textures/effects/specularB.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/powerups/ammo/amtesla.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/weapons2/garand/rifle2
{
	{
		map textures/effects/envmap_slateH2.tga
		rgbGen lightingDiffuse
		tcMod scale 1.5 1.5
		tcGen environment 
	}
	{
		map models/weapons2/garand/rifle2.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
	{
		map textures/dtx/ametal2.tga
		blendfunc filter
		rgbGen identity
		tcMod scale 6 6
		detail
	}
	{
		map models/weapons2/garand/rifle2_glow.tga
		blendfunc add
		rgbGen wave sawtooth 0.8 0.1 0 8 
	}
}

models/weapons2/c4_dynamite/dynomite1a
{
	{
		map textures/effects/specular3.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/c4_dynamite/dynomite1a.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/multiplayer/supplies/ammobox
{
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/supplies/ammobox.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/multiplayer/supplies/healthbox
{
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/supplies/healthbox.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/multiplayer/mp40/mp40
{
	{
		map textures/effects/envmap_mp.tga
		rgbGen lightingDiffuse
		tcMod scale 2 2
		tcGen environment 
	}
	{
		map models/multiplayer/mp40/mp40.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
}

